UoMResearchIT/RSESkillsGraph

people.json
Added my name and list of skills in people.json
=> Adds skills for Catherine McGuire

people.json
Adds skills for Francisco Herrerias Azcue.
=> Updated people.json to include Francisco Herrerias Azcue

people.json
Added new section to people.json for Nigel Green
=> Added Nigel Green to people.json

people.json
Added new section to people.json for Jia Wu.
=> Add interests for Jia Wu

people.json
=> Add interests for Hugo Chu

people.json
Adding myself to the skills graph.
=> feat: add Chris Fullerton

people.json
Hello,
I added my info to the .JSON file.
=> Added EA_Info

people.json
Updated the skills graph with my details.
=> Added profile for Emma Simpson

people.json
=> Adina Rahim

people.json
Add a few more bits and pieces to the pile of things I know.
=> Update of Donal Fellows's skills

people.json
Added object for Mike Jones as last block in people.json.
=> Added Mike Jones to people.json

people.json
Change "Natural environmental" to "Environmental Science"
=> Update people.json for Jonny Taylor

people.json
I have revised the suggested entries to ensure their compatibility with Wikipedia.
=> Make updates as per wikipedia suggestions

people.json, test_application.py, title_exceptions.json
Fixes #50 
Note that there are still issues with macOS and iOS in the tests.  These would require a different exception mechanism, or else they have to be changed (or we ignore canonicalisation).
=> Add exceptions

README.md
Resolves #63 and #89 - how do you use this tool without installing it on your laptop
=> Add deployed site link to readme

people.json
An initial list as part of my induction.
=> Add Benito Matischen

people.json
An initial list as part of my induction.
=> add Chris Lam

people.json
=> Add Toni Price

people.json
Added a couple of things and removed some!
=> Update skills for AJ

people.json
- Add new skillz
- Fix some capitals to be consistent with wikipedia
=> JonnyTaylor nov24 update

people.json
=>  Add interests to skill graph
